# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLI_RAZAOSOCIAL', models.CharField(max_length=255)),
                ('CLI_FANTASIA', models.CharField(max_length=255)),
                ('CLI_IE', models.CharField(max_length=20)),
                ('CLI_IM', models.CharField(max_length=20)),
                ('CLI_EMAIL', models.CharField(max_length=255)),
                ('CLI_FONE', models.CharField(max_length=13)),
            ],
        ),
    ]
