# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_DESCRICAO', models.CharField(max_length=150)),
                ('CAT_DESC_RED', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAR_DESCRICAO', models.CharField(max_length=150)),
                ('MAR_DESC_RED', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_DESCRICAO', models.CharField(max_length=150)),
                ('PRO_CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Categoria')),
                ('PRO_MARCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UND_DESCRICAO', models.CharField(max_length=150)),
                ('UND_DESC_RED', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CLI_EMAIL',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='promocao',
            name='PROM_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Cliente'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='PROM_PRODUTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='PRO_UNIDADE_MEDIDA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.UnidadeMedida'),
        ),
    ]
