# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_auto_20171007_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameField(
            model_name='unidademedida',
            old_name='UND_DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='unidademedida',
            old_name='UND_DESC_RED',
            new_name='descricao_reduzida',
        ),
    ]
