# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_auto_20171007_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='CAT_DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='CAT_DESC_RED',
            new_name='descricao_reduzida',
        ),
    ]
