# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_auto_20171007_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_fantasia']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao', 'marca']},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ['produto'], 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'ordering': ['descricao'], 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_FONE',
            new_name='fone',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_IE',
            new_name='inscricao_estadual',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_IM',
            new_name='inscricao_municipal',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_FANTASIA',
            new_name='nome_fantasia',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CLI_RAZAOSOCIAL',
            new_name='razao_social',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='MAR_DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='PRO_CATEGORIA',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='PRO_DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='PRO_MARCA',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='PRO_UNIDADE_MEDIDA',
            new_name='unidade_de_medida',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='PROM_CLIENTE',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='PROM_PRODUTO',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao_reduzida',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='MAR_DESC_RED',
        ),
        migrations.RemoveField(
            model_name='unidademedida',
            name='descricao_reduzida',
        ),
    ]
