# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_auto_20171007_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
