# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0006_cliente_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['descricao_marca']},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='descricao',
            new_name='descricao_marca',
        ),
    ]
