# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0007_auto_20171007_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='descricao_marca',
            new_name='descricao',
        ),
    ]
