# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0008_auto_20171007_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_fantasia', 'razao_social']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['descricao_marca']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'ordering': ['descricao'], 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='descricao',
            new_name='descricao_marca',
        ),
    ]
