# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0009_auto_20171007_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
