# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0014_auto_20171007_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Marca'),
        ),
    ]
