# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0019_remove_produto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='marca',
        ),
    ]
