# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0024_auto_20171007_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_de_medida',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
        migrations.DeleteModel(
            name='UnidadeMedida',
        ),
    ]
