# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supermarket', '0025_auto_20171007_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255, null=True)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('fone', models.CharField(max_length=13)),
            ],
            options={
                'ordering': ['nome_fantasia', 'razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_marca', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['descricao_marca'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('imagem', models.ImageField(null=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.Marca')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Cliente')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.Marca')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Produto')),
            ],
            options={
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.UnidadeMedida'),
        ),
    ]
