# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0026_auto_20171007_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
