# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0028_auto_20171007_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
