# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0029_auto_20171007_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
