# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0030_auto_20171007_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='data_fim',
            field=models.DateField(null=True),
        ),
    ]
