# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0031_auto_20171007_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
