# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0032_auto_20171007_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
