# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0033_auto_20171007_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Marca')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Produto')),
            ],
            options={
                'verbose_name_plural': 'Promoções',
            },
        ),
    ]
