# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0034_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ['produto', 'marca', 'valor'], 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
