# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0035_auto_20171007_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'ordering': ['produto', 'valor'], 'verbose_name_plural': 'Promoções'},
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='marca',
        ),
    ]
