# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0042_auto_20171009_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_produtos'),
        ),
    ]
