# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0044_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermarket.Cliente'),
            preserve_default=False,
        ),
    ]
