# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0045_userprofile_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.Cliente'),
        ),
    ]
